apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - localstack.yaml
  - external-secrets.yaml
  - crossplane-base.yaml
  - crossplane-config.yaml
  - crossplane-provider-aws.yaml
  - crossplane-provider-kubernetes.yaml
  - traefik.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - alloy.yaml
  - agent-sandbox.yaml
  - openshell.yaml
  - sandbox-platform.yaml
  - kyverno.yaml
  - sandbox-policies.yaml
